#!/usr/bin/env python3
from pathlib import Path
from tools.runner.io_utils import write_text, touch_json, MB

def run() -> None:
    client_brief = MB / "plan/client_brief.md"
    if not client_brief.exists():
        raise SystemExit("client_brief.md missing; cannot generate backlog.")
    write_text(MB / "plan/product_backlog.yaml", "# backlog: generated by runner\n", role="product_owner_ai")
    touch_json(MB / "plan/acceptance_criteria.json", {"criteria": []}, role="product_owner_ai")

