name: Attach Mapping CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov pytest-xdist

      - name: Run attach mapping tests
        working-directory: frameworks/fwk-001-cursor-rules
        run: |
          pytest -q tests/unit/test_rule_attach_mapping.py tests/unit/test_rule_attach_mapping_more.py
